{% set python_min = "3.10" %}
{% set name = "fastberry" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastberry-{{ version }}.tar.gz
  sha256: 3e5418609b8ad4334bbeb5afa5e6c51f36d218e40c2ac7ead10a0c3414362a0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - startproject = fastberry.scripts.start_project:cli

requirements:
  host:
    - pdm-pep517 >=1.0.0
    - pip
    - python {{ python_min }}
  run:
    - click >=8.1.3
    - fastapi >=0.88.0
    - pre-commit >=2.20.0
    - python >={{ python_min }}
    - spoc >=0.1.5
    - strawberry-graphql >=0.146.0
    - uvicorn >=0.18.3

test:
  imports:
    - fastberry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hlop3z/fastberry
  doc_url: https://hlop3z.github.io/fastberry/
  summary: GraphQL Made Easy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
