{% set python_min = "3.10" %}
{% set name = "fastberry" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastberry-{{ version }}.tar.gz
  sha256: b9bb69736861f330a15a21a7f46541a06522b41e33608c40a2d557ac40792147

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - startproject = fastberry.scripts.start_project:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - strawberry-graphql >=0.200
    - django >=4.2

test:
  imports:
    - fastberry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hlop3z/fastberry
  doc_url: https://hlop3z.github.io/fastberry/
  summary: GraphQL Made Easy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
