{% set name = "fastberry" %}
{% set version = "0.0.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastberry-{{ version }}.tar.gz
  sha256: 614294cb8b1c8a83b80b37a316fd8308d06d0dba2d3ab54f2353f1dcd8ee2b50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - startproject = fastberry.scripts.start_project:cli

requirements:
  host:
    - pdm-pep517 >=1.0.0
    - pip
    - python >=3.10
  run:
    - click >=8.1.3
    - fastapi >=0.88.0
    - python >=3.10
    - spoc >=0.1.5
    - strawberry-graphql >=0.146.0
    - uvicorn >=0.18.3

test:
  imports:
    - fastberry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hlop3z/fastberry
  doc_url: https://hlop3z.github.io/fastberry/
  summary: GraphQL Made Easy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
